package com.dylanhouston.rollthedice;

public enum LetterPreferences {
    a_included,
    b_included,
    c_included,
    d_included,
    e_included,
    f_included,
    g_included,
    h_included,
    i_included,
    j_included,
    k_included,
    l_included,
    m_included,
    n_included,
    o_included,
    p_included,
    q_included,
    r_included,
    s_included,
    t_included,
    u_included,
    v_included,
    w_included,
    x_included,
    y_included,
    z_included
}
